// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0lBH7jqerH0OY0xt72uNs9DeH_CS4DdQ',
    appId: '1:540713378828:web:211e931ee597928bfeba29',
    messagingSenderId: '540713378828',
    projectId: 'individu-assignment',
    authDomain: 'individu-assignment.firebaseapp.com',
    databaseURL: 'https://individu-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'individu-assignment.appspot.com',
    measurementId: 'G-MYK3927BTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQwunGqvi032Owfh7zPMP677_z0Zsp_g',
    appId: '1:540713378828:android:d427a78401bf2f7cfeba29',
    messagingSenderId: '540713378828',
    projectId: 'individu-assignment',
    databaseURL: 'https://individu-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'individu-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwTyYd92rJDfq3NYoS9Ghr272mkn0bAg',
    appId: '1:540713378828:ios:863ea8b1375df09efeba29',
    messagingSenderId: '540713378828',
    projectId: 'individu-assignment',
    databaseURL: 'https://individu-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'individu-assignment.appspot.com',
    iosBundleId: 'com.example.haohaoindividu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIwTyYd92rJDfq3NYoS9Ghr272mkn0bAg',
    appId: '1:540713378828:ios:863ea8b1375df09efeba29',
    messagingSenderId: '540713378828',
    projectId: 'individu-assignment',
    databaseURL: 'https://individu-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'individu-assignment.appspot.com',
    iosBundleId: 'com.example.haohaoindividu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0lBH7jqerH0OY0xt72uNs9DeH_CS4DdQ',
    appId: '1:540713378828:web:cbbe451d6fad803efeba29',
    messagingSenderId: '540713378828',
    projectId: 'individu-assignment',
    authDomain: 'individu-assignment.firebaseapp.com',
    databaseURL: 'https://individu-assignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'individu-assignment.appspot.com',
    measurementId: 'G-RNE6NMYFS1',
  );
}
